//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITRA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Наряд
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Наряд()
        {
            this.Наряд_Сотрудник = new HashSet<Наряд_Сотрудник>();
            this.Отчёт = new HashSet<Отчёт>();
        }
    
        public int Номер { get; set; }
        public int ID_Оборудования { get; set; }
        public System.DateTime Дата { get; set; }
        public Nullable<int> ID_Исполнителя { get; set; }
        public int ID_Состояния { get; set; }
        public int ID_Шаблона { get; set; }
        public string Описание { get; set; }
    
        public virtual Оборудование Оборудование { get; set; }
        public virtual Состояние Состояние { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Наряд_Сотрудник> Наряд_Сотрудник { get; set; }
        public virtual Шаблон Шаблон { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отчёт> Отчёт { get; set; }
    }
}
