//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITRA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отчёт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Отчёт()
        {
            this.Расход = new HashSet<Расход>();
        }
    
        public int ID { get; set; }
        public int Номер_Наряда { get; set; }
        public System.DateTime Дата { get; set; }
        public string Результат { get; set; }
    
        public virtual Наряд Наряд { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расход> Расход { get; set; }
    }
}
